### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by ridaarif98** [julie-ify/Leaderboard#4]
Hi @julie-ify ,
     Your project is complete! The way you implement `API`  is different and I really like it, there is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by julie-ify** [comment]
Thanks, guys for reviewing my code 🤝
